### ISSUE TITLE
Tabular Steps: can't delete the first row.

### ISSUE THREAD

**Issue by nievesav** [buttflattery/yii2-formwizard#69]
I'm using the tabular step, but i can't delete the first row because the option not showing. 
In the others rows show the cross but in the first does't.

Sorry but my english is not very good!
thanks!

**Comment by buttflattery** [comment]
Because that is the default row and cannot be deleted, that is a limitation so far. @nievesav

**Comment by nievesav** [comment]
Ok.
In the edition when i have one or more rows, i need to delete the first because is incorrect.

**Comment by buttflattery** [comment]
hmm ok let me see if i can push an update for that scenario after i verify it once.

**Comment by buttflattery** [comment]
sorry for being late, you can pull the latest code by running `composer update` now there is a remove icon with the default row when editing, and if there is only one row in the tabular step , it will clear the inputs instead of remove the row. @nievesav , i am closing the issue now if you face problems  you can open the issue again.
