### ISSUE TITLE
Issue using kartik\widget\DepDrop in FormWizard

### ISSUE THREAD

**Issue by idowstech** [buttflattery/yii2-formwizard#8]
Using the Dependent dropdown widget by kartik acts strange as the dropdown always shows the default one without css even if i specify the `"type"=>DepDrop::TYPE_SELECT2` in the DepDrop options. although it is working ok and populates the options on runtime if the parent dropdown changes

**Comment by buttflattery** [comment]
Yes you are right it was because of the following lines


       //remove the type and itemList from options
        unset($options['type']);
        unset($options['itemsList']);

        //widget
        if ($widget) {
            return $field->widget($widget, $options)->label($label, $labelOptions);
        }


as you can see i am unsetting two options from the `options` option namely `type` and `itemList` inside the `createCustomInput()` function line `551 onwards` to `Line 558` because these 2 options were used by the widget for the checkbox and radio list input options and the other one for creting the field type mentioned in the option for the `fieldConfig` ,and not needed inside the field Input options for the active form which are created in the next line but in case of widget i am returning the control from inside the check and in case of widget there could be any option with any name that can match any of my options so i just need to unset the options after the widget check , just need to swap these two lines.
